ecommerce/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('store.urls')),
]

# To display images
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

store/urls.py
from store.forms import LoginForm, PasswordChangeForm, PasswordResetForm, SetPasswordForm
from django.urls import path
from . import views
from django.contrib.auth import views as auth_views


app_name = 'store'


urlpatterns = [
    path('', views.home, name="home"),
    path('search/', views.search, name="search"),
    # URL for Cart and Checkout
    path('add-to-cart/', views.add_to_cart, name="add-to-cart"),
    path('remove-cart/<int:cart_id>/', views.remove_cart, name="remove-cart"),
    path('plus-cart/<int:cart_id>/', views.plus_cart, name="plus-cart"),
    path('minus-cart/<int:cart_id>/', views.minus_cart, name="minus-cart"),
    path('update-cart/<int:cart_id>/', views.update_cart, name="update-cart"),
    path('cart/', views.cart, name="cart"),
    path('wishlist/', views.wishlist, name="wishlist"),
    path('add-to-wishlist/<int:product_id>/', views.add_to_wishlist, name="add-to-wishlist"),
    path('remove-wishlist/<int:wishlist_id>/', views.remove_wishlist, name="remove-wishlist"),
    path('checkout/', views.checkout, name="checkout"),
    path('orders/', views.orders, name="orders"),
    path('invoice/<int:order_id>', views.generate_invoice, name="invoice"),

    #URL for Products
    path('chatbot/', views.chatbot, name="chatbot"),
    path('product/<slug:slug>/', views.detail, name="product-detail"),
    path('categories/', views.all_categories, name="all-categories"),
    path('<slug:slug>/', views.category_products, name="category-products"),

    path('shop/', views.shop, name="shop"),

    # URL for Authentication
    path('accounts/register/', views.RegistrationView.as_view(), name="register"),
    path('accounts/verify_otp', views.OTPVerificationView.as_view(), name="verify_otp"),
    path('accounts/login/', auth_views.LoginView.as_view(template_name='account/login.html', authentication_form=LoginForm), name="login"),
    path('accounts/profile/', views.profile, name="profile"),
    path('accounts/add-address/', views.AddressView.as_view(), name="add-address"),
    path('accounts/remove-address/<int:id>/', views.remove_address, name="remove-address"),
    path('accounts/logout/', auth_views.LogoutView.as_view(next_page='store:login'), name="logout"),

    path('accounts/password-change/', auth_views.PasswordChangeView.as_view(template_name='account/password_change.html', form_class=PasswordChangeForm, success_url='/accounts/password-change-done/'), name="password-change"),
    path('accounts/password-change-done/', auth_views.PasswordChangeDoneView.as_view(template_name='account/password_change_done.html'), name="password-change-done"),

    path('accounts/password-reset/', auth_views.PasswordResetView.as_view(template_name='account/password_reset.html', form_class=PasswordResetForm, success_url='/accounts/password-reset/done/'), name="password-reset"), # Passing Success URL to Override default URL, also created password_reset_email.html due to error from our app_name in URL
    path('accounts/password-reset/done/', auth_views.PasswordResetDoneView.as_view(template_name='account/password_reset_done.html'), name="password_reset_done"),
    path('accounts/password-reset-confirm/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(template_name='account/password_reset_confirm.html', form_class=SetPasswordForm, success_url='/accounts/password-reset-complete/'), name="password_reset_confirm"), # Passing Success URL to Override default URL
    path('accounts/password-reset-complete/', auth_views.PasswordResetCompleteView.as_view(template_name='account/password_reset_complete.html'), name="password_reset_complete"),

    path('product/test/', views.test, name="test"),

    #FOR ADMIN
    path('admin_category',views.admin_category, name="admin_category"),
    path('admin_add_cat',views.admin_add_cat, name="admin_add_cat"),

    path('admin_brand',views.admin_brand, name="admin_brand"),
    path('admin_add_brand',views.admin_add_brand, name="admin_add_brand"),
    
    path('admin_product',views.admin_product, name="admin_product"),
    path('admin_add_product',views.admin_add_product, name="admin_add_product"),


    
]

store/views.py
from io import BytesIO
import random
import django
from django.contrib.auth.models import User
from ecommerce.settings import RAZORPAY_KEY_ID, RAZORPAY_KEY_SECRET
from store.models import Address, Cart, Category, Order, Product, Wishlist,Review,Brand
from django.shortcuts import redirect, render, get_object_or_404
from .forms import RegistrationForm, AddressForm
from django.contrib import messages
from django.views import View
import decimal
from django.contrib.auth.decorators import login_required
from django.utils.decorators import method_decorator # for Class Based Views
from django.views.decorators.csrf import csrf_exempt
import razorpay
from django.template.loader import get_template
from xhtml2pdf import pisa
from django.http import HttpResponse
client = razorpay.Client(auth=(RAZORPAY_KEY_ID, RAZORPAY_KEY_SECRET))
from django.core.mail import send_mail
from django.core.mail import EmailMessage



# Create your views here.

def home(request):
    if request.method == 'POST':
        order_id = request.POST.get('order_id')
        status = request.POST.get('status')
        order = get_object_or_404(Order,id=order_id)
        order.status = status
        order.save()
        
    categories = Category.objects.filter(is_active=True, is_featured=True)[:3]
    products = Product.objects.filter(is_active=True, is_featured=True)[:8]
    orders = Order.objects.all()
    choices = ['Pending','Accepted','Packed','On The Way','Delivered','Cancelled',]
    context = {
        'STATUS_CHOICES' : choices,
        'categories': categories,
        'products': products,
        'orders' : orders,
    }
    return render(request, 'store/index.html', context)

from django.db.models import Q

def search(request):
    search_text = request.POST.get('search', '').strip()

    # Fetch categories and products that match the search query
    categories = Category.objects.filter(is_active=True).order_by('created_at')
    products = Product.objects.filter(is_active=True)

    # If search query is not empty, filter products based on search query
    if search_text:
        # Search across multiple fields (title, description, etc.) using OR condition
        products = products.filter(
            Q(title__icontains=search_text) |
            Q(short_description__icontains=search_text) |
            Q(category__title__icontains=search_text)
        ).distinct()

    context = {
        'search_text': search_text,
        'categories': categories,
        'products': products,
    }

    return render(request, 'store/search_result.html', context)



def detail(request, slug):
    if request.method == 'POST':
        user = request.user
        product_id = request.POST.get('product_id')
        product = get_object_or_404(Product,id=product_id)
        rating = request.POST.get('rating')
        text = request.POST.get('text')
        Review(user=user,product=product,rating=rating,text=text).save()

    product = get_object_or_404(Product, slug=slug)
    category = get_object_or_404(Category,id=product.category.id)
    related_products = Product.objects.exclude(id=product.id).filter(is_active=True, category=product.category)
    reviews = Review.objects.filter(product=product)
    sum=0
    count=0
    for i in reviews:
        sum+=i.rating
        count+=1
    if count>0:
        average_rating = int(sum/count)
    else:
        average_rating=0

    context = {
        'category' : category,
        'product': product,
        'related_products': related_products,
        'reviews' : reviews,
        'average_rating' : average_rating,

    }

    return render(request, 'store/detail.html', context)


def all_categories(request):
    categories = Category.objects.filter(is_active=True).order_by('created_at')
    return render(request, 'store/categories.html', {'categories':categories})


def category_products(request, slug):
    category = get_object_or_404(Category, slug=slug)
    products = Product.objects.filter(is_active=True, category=category)
    categories = Category.objects.filter(is_active=True).order_by('created_at')
    context = {
        'category': category,
        'products': products,
        'categories': categories,
    }
    return render(request, 'store/category_products.html', context)


# Authentication Starts Here

class RegistrationView(View):
    def get(self, request):
        form = RegistrationForm()
        return render(request, 'account/register.html', {'form': form})
    
    def post(self, request):
        form = RegistrationForm(request.POST)
        if form.is_valid():
            email = form.cleaned_data['email']
            request.session['data'] = form.cleaned_data

            # Generate OTP
            otp = ''.join(random.choices('0123456789', k=6))
            request.session['otp'] = otp

            # Send OTP to user's email
            sender = "prajeshiyer@gmail.com"
            recipient = [email]
            subject_to_applicant = "E-Commerce - OTP For Registration"
            message_to_applicant = "Use this OTP while registration : "+otp
            send_mail(subject_to_applicant, message_to_applicant, sender, recipient)

            return redirect('store:verify_otp')
        
        return render(request, 'account/register.html', {'form': form})

class OTPVerificationView(View):
    def get(self, request):
        return render(request, 'account/verify_otp.html')
    
    def post(self, request):
        otp = request.POST.get('otp')
        if 'otp' in request.session and request.session['otp'] == otp:
            # OTP is valid, proceed with registration
            form = RegistrationForm(request.session['data'])
            if form.is_valid():
                form.save()
                messages.success(request, "Congratulations! Registration Successful!")
                del request.session['otp']  # Clear OTP from session
                del request.session['data']  # Clear form data from session
                return redirect('store:home')
        # Invalid OTP or no OTP found in session
        messages.error(request, "Invalid OTP. Please try again.")
        return redirect('verify_otp')

    
def chatbot(request):
    return render(request, 'store/chatbot.html')
        

@login_required
def profile(request):
    if request.user.is_staff == True:
        return redirect('store:home')
    
    addresses = Address.objects.filter(user=request.user)
    orders = Order.objects.filter(user=request.user)
    return render(request, 'account/profile.html', {'addresses':addresses, 'orders':orders})


@method_decorator(login_required, name='dispatch')
class AddressView(View):
    def get(self, request):
        form = AddressForm()
        return render(request, 'account/add_address.html', {'form': form})

    def post(self, request):
        form = AddressForm(request.POST)
        if form.is_valid():
            user=request.user
            locality = form.cleaned_data['locality']
            city = form.cleaned_data['city']
            state = form.cleaned_data['state']
            reg = Address(user=user, locality=locality, city=city, state=state)
            reg.save()
            messages.success(request, "New Address Added Successfully.")
        return redirect('store:profile')


@login_required
def remove_address(request, id):
    a = get_object_or_404(Address, user=request.user, id=id)
    a.delete()
    messages.success(request, "Address removed.")
    return redirect('store:profile')

#### ---- WISHLIST ----####

@login_required
def add_to_wishlist(request, product_id):
    user = request.user
    product = get_object_or_404(Product, id=product_id)
    item_already_in_wishlist = Wishlist.objects.filter(product=product_id, user=user)
    if item_already_in_wishlist:
        return redirect('store:wishlist')
    else:
        Wishlist(user=user, product=product).save()
        return redirect('store:wishlist')

@login_required
def wishlist(request):
    user = request.user
    cart_products = Wishlist.objects.filter(user=user)

    context = {
        'cart_products': cart_products,
    }
    return render(request, 'store/wishlist.html', context)


@login_required
def remove_wishlist(request, wishlist_id):
    if request.method == 'GET':
        c = get_object_or_404(Wishlist, id=wishlist_id)
        c.delete()
        messages.success(request, "Product removed from Wishlist.")
    return redirect('store:wishlist')

#### ---- CART ----####

@login_required
def add_to_cart(request):
    user = request.user
    product_id = request.GET.get('prod_id')
    product = get_object_or_404(Product, id=product_id)
    # Check whether the Product is alread in Cart or Not
    item_already_in_cart = Cart.objects.filter(product=product_id, user=user)
    if item_already_in_cart:
        # cp = get_object_or_404(Cart, product=product_id, user=user)
        # product = get_object_or_404(Product, id=cp.product.id)
        # if product.stock > cp.quantity:
        #     cp.quantity += 1
        #     cp.save()
        # else:
        messages.success(request, "Item already in cart!!")
    else:
        if product.stock > 0:
            Cart(user=user, product=product).save()
        else:
            messages.success(request, "Product is out of stock")   
    
    return redirect('store:cart')


@login_required
def cart(request):
    user = request.user
    cart_products = Cart.objects.filter(user=user)

    # Display Total on Cart Page
    amount = decimal.Decimal(0)
    
    # using list comprehension to calculate total amount based on quantity and shipping
    cp = [p for p in Cart.objects.all() if p.user==user]
    if cp:
        for p in cp:
            temp_amount = (p.quantity * p.product.price)
            amount += temp_amount

    # Customer Addresses
    addresses = Address.objects.filter(user=user)
    shipping_amount = float(amount)*0.05
    gst_amount = float(amount)*0.18
    total_amount = float(amount) + float(shipping_amount) + gst_amount

templates/store/cart.html
{% extends 'base.html' %}
{% load static %}
{% load humanize %}

    {% block content %}

    <style>
      input[type=submit] { 
        width: 100%; 
        padding: 12px 20px; 
        margin: 8px 0; 
        font-size: 20px;       
        box-sizing: border-box; 
        font-weight: bold;
        background-color: #292929;
        color: white;
      }
    </style>
      <div class="container">
        <!-- HERO SECTION-->
        <section class="py-5 bg-light">
          <div class="container">
            <div class="row px-4 px-lg-5 py-lg-4 align-items-center">
              <div class="col-lg-6">
                <h1 class="h2 text-uppercase mb-0">Cart</h1>
              </div>
              <div class="col-lg-6 text-lg-right">
                <nav aria-label="breadcrumb">
                  <ol class="breadcrumb justify-content-lg-end mb-0 px-0">
                    <li class="breadcrumb-item"><a href="index.html">Home</a></li>
                    <li class="breadcrumb-item active" aria-current="page">Cart</li>
                  </ol>
                </nav>
              </div>
            </div>
          </div>
        </section>

        {% if cart_products %}
        <section class="py-5">
          <h2 class="h5 text-uppercase mb-4">Shopping cart</h2>

          {% include 'partials/_messages.html' %}

          <div class="row">
            <div class="col-lg-8 mb-4 mb-lg-0">
              <!-- CART TABLE-->
              <div class="table-responsive mb-4">
                <table class="table">
                  <thead class="bg-light">
                    <tr>
                      <th class="border-0" scope="col"> <strong class="text-small text-uppercase">Product</strong></th>
                      <th class="border-0" scope="col"> <strong class="text-small text-uppercase">Price</strong></th>
                      <th class="border-0" scope="col"> <strong class="text-small text-uppercase">Quantity</strong></th>
                      <th class="border-0" scope="col"> <strong class="text-small text-uppercase">Total</strong></th>
                      <th class="border-0" scope="col"> </th>
                    </tr>
                  </thead>
                  <tbody>

                    {% for cart_product in cart_products %}
                    <tr>
                      <th class="pl-0 border-0" scope="row">
                        <div class="media align-items-center">

                          {% if cart_product.product.product_image %}
                            <a class="reset-anchor d-block animsition-link" href="{% url 'store:product-detail' cart_product.product.slug %}"><img src="{{cart_product.product.product_image.url}}" alt="{{cart_product.product.title}}" width="70"/></a>
                          {% else %}
                            <a class="reset-anchor d-block animsition-link" href="{% url 'store:product-detail' cart_product.product.slug %}"><img src="{% static 'img/product-detail-3.jpg' %}" alt="{{cart_product.product.title}}" width="70"/></a>
                          {% endif %}

                          <div class="media-body ml-3"><strong class="h6"><a class="reset-anchor animsition-link" href="{% url 'store:product-detail' cart_product.product.slug %}">{{cart_product.product.title}}</a></strong></div>
                        </div>
                      </th>
                      <td class="align-middle border-0">
                        <p class="mb-0 small">₹{{cart_product.product.price}}</p>
                      </td>
                      <td class="align-middle border-0">
                        <!--<div class="border d-flex align-items-center justify-content-between px-3"><span class="small text-uppercase text-gray headings-font-family">Quantity</span>
                          <div class="quantity">
                            <a href="{% url 'store:minus-cart' cart_product.id %}" class="dec-btn p-0 ml-2"><i class="fas fa-minus"></i></a>
                            {% comment %} <button class="dec-btn p-0"><i class="fas fa-caret-left"></i></button> {% endcomment %}
                            <input class="form-control form-control-sm border-0 shadow-0 p-0" type="text" name= "quantity" value="{{cart_product.quantity}}"/>
                            {% comment %} <button class="inc-btn p-0"><i class="fas fa-caret-right"></i></button> {% endcomment %}
                            <a href="{% url 'store:plus-cart' cart_product.id %}" class="inc-btn p-0"><i class="fas fa-plus"></i></a>                        
                          </div>
                        </div>-->

                        <div class="input-group mb-3">
                          <form action="{% url 'store:update-cart' cart_product.id %}">
                          <input type="number" placeholder="{{cart_product.quantity}}" name="qty" class="form-control">
                          <div class="input-group-append">
                            <button class="btn btn-outline-secondary" type="submit">Verify</button>
                          </div>
                          </form>
                        </div>

                      </td>
                      <td class="align-middle border-0">
                        <p class="mb-0 small">₹{{cart_product.total_price|intcomma}}</p>
                      </td>
                      <td class="align-middle border-0"><a class="reset-anchor" href="{% url 'store:remove-cart' cart_product.id %}"><i class="fas fa-trash-alt small text-muted"></i></a></td>
                    </tr>
                    {% endfor %}

                  </tbody>
                </table>
              </div>
              <!-- CART NAV-->
              <div class="bg-light px-4 py-3">
                <div class="row align-items-center text-center">
                  <div class="col-md-6 mb-3 mb-md-0 text-md-left"><a class="btn btn-link p-0 text-dark btn-sm" href="{% url 'store:home' %}"><i class="fas fa-long-arrow-alt-left mr-2"> </i>Continue shopping</a></div>
                  <!-- <div class="col-md-6 text-md-right"><a class="btn btn-outline-dark btn-sm" href="checkout.html">Procceed to checkout<i class="fas fa-long-arrow-alt-right ml-2"></i></a></div> -->
                </div>
              </div>
            </div>
            <!-- ORDER TOTAL-->
            <div class="col-lg-4">
              <div class="card border-0 rounded-0 p-lg-4 bg-light">
                <div class="card-body">
                  <h5 class="text-uppercase mb-4">Cart total</h5>
                  <ul class="list-unstyled mb-0">
                    <li class="d-flex align-items-center justify-content-between"><strong class="text-uppercase small font-weight-bold">Subtotal</strong><span class="text-muted small">₹{{amount|intcomma}}</span></li>
                    <li class="d-flex align-items-center justify-content-between"><strong class="text-uppercase small font-weight-bold">Shipping Charge</strong><span class="text-muted small">+ ₹{{shipping_amount}}</span></li>
                    <li class="d-flex align-items-center justify-content-between"><strong class="text-uppercase small font-weight-bold">GST</strong><span class="text-muted small">+ ₹{{gst_amount}}</span></li>
                    <li class="border-bottom my-2"></li>
                    <li class="d-flex align-items-center justify-content-between mb-4"><strong class="text-uppercase small font-weight-bold">Total</strong><span>₹{{total_amount|intcomma}}</span></li>
                    <li>

                      {% comment %} <form action="#">
                        <div class="form-group mb-0">
                          <input class="form-control" type="text" placeholder="Enter your coupon">
                          <button class="btn btn-dark btn-sm btn-block" type="submit"> <i class="fas fa-gift mr-2"></i>Apply coupon</button>
                        </div>
                      </form> {% endcomment %}

                    </li>
                  </ul>

                  
                  <h5 class="text-uppercase my-5">Select Shipping Address</h5>
                  
                  <form action="{% url 'store:checkout' %}" id="myform">

                    {% if addresses %}
                      {% for address in addresses %}
                        <div class="mb-3">
                        <input type="radio" name="address" value="{{address.id}}" required> <strong>Address {{forloop.counter}}</strong> <br>
                        ( {{address.locality}}, {{address.city}}, {{address.state}} )
                        </div>
                      {% endfor %}
                      <!-- Set up a container element for the button -->
                      <div class="text-end" id="paypal-button-container"></div>

                      {% comment %} For Cash on Delivery {% endcomment %}
                      <button type="submit" class="btn btn-success w-100 mb-1"> ₹ Cash on Delivery</button>
                    {% else %}
                        <a href="{% url 'store:add-address' %}">Add Shipping address for checkout</a>
                    {% endif %}

                    
                
                  </form>

                </div>
              </div>
            </div>

          </div>
        </section>
        
        {% else %}

          <div class="text-center py-5">
            <h3 class="mb-3">Your cart is empty.</h3>
            <a href="{% url 'store:home' %}"><i class="fas fa-long-arrow-alt-left mr-2"> </i>Continue shopping</a>
          </div>

        {% endif %}

      </div>
      {% endblock content %}

      {% block payment-gateway %}
        <!-- Include the PayPal JavaScript SDK -->
    <script src="https://www.paypal.com/sdk/js?client-id=YOUR-PAYPAL-CLIENT-ID&currency=USD"></script>

    <script>
        // Render the PayPal button into #paypal-button-container
        paypal.Buttons({

            // Set up the transaction
            createOrder: function(data, actions) {
                return actions.order.create({
                    purchase_units: [{
                        amount: {
                            value: '{{total_amount}}'
                        }
                    }]
                });
            },

            // Finalize the transaction
            onApprove: function(data, actions) {
                return actions.order.capture().then(function(details) {
                    // Show a success message to the buyer
                    alert('Transaction completed by ' + details.payer.name.given_name + '!');
                    // Savind Order in Database after Payment Success
                    document.getElementById('myform').submit();
                });
            }


        }).render('#paypal-button-container');
    </script>
      {% endblock payment-gateway %}

templates/store/chatbot.html
{% extends 'base.html' %}
{% load static %}

    {% block content %}
    <style>
        .chatbot {
            display: block;
            margin-left: 500px;
        }

        iframe {
            font-family: Arial, sans-serif;
            font-size: 14px;
        }

        /* Change the color of the chatbot text */
        .chat-container p {
            color: #333;
        }

        /* Change the color of the chatbot buttons */
        .df-button {
            background-color: #4285f4;
            color: #fff;    
        }

        /* Change the border radius of the chatbot buttons */
        .df-button {
            border-radius: 20px;
        }

        /* Change the hover effect of the chatbot buttons */
        .df-button:hover {
            background-color: #3367d6;
        }
        
    </style>
    <div class="chatbot">
        <iframe
        width="500"
        height="500"
        src="https://console.dialogflow.com/api-client/demo/embedded/a2b49fd2-1dcf-4b04-8d11-7c6eaced0e4e">
        </iframe>
    </div>
    {% endblock content %}

templates/store/wishlist.html
{% extends 'base.html' %}
{% load static %}
{% load humanize %}

    {% block content %}
      <div class="container">
        <!-- HERO SECTION-->
        <section class="py-5 bg-light">
          <div class="container">
            <div class="row px-4 px-lg-5 py-lg-4 align-items-center">
              <div class="col-lg-6">
                <h1 class="h2 text-uppercase mb-0">Wishlist</h1>
              </div>
              <div class="col-lg-6 text-lg-right">
                <nav aria-label="breadcrumb">
                  <ol class="breadcrumb justify-content-lg-end mb-0 px-0">
                    <li class="breadcrumb-item"><a href="index.html">Home</a></li>
                    <li class="breadcrumb-item active" aria-current="page">Wishlist</li>
                  </ol>
                </nav>
              </div>
            </div>
          </div>
        </section>

        {% if cart_products %}
        <section class="py-5">
          <h2 class="h5 text-uppercase mb-4">My WIshlist</h2>

          {% include 'partials/_messages.html' %}

          <div class="row">
            <div class="col-lg-8 mb-4 mb-lg-0">
              <!-- CART TABLE-->
              <div class="table-responsive mb-4">
                <table class="table">
                  <thead class="bg-light">
                    <tr>
                      <th class="border-0" scope="col"> <strong class="text-small text-uppercase">Product</strong></th>
                    </tr>
                  </thead>
                  <tbody>

                    {% for cart_product in cart_products %}
                    <tr>
                      <th class="pl-0 border-0" scope="row">
                        <div class="media align-items-center">

                          {% if cart_product.product.product_image %}
                            <a class="reset-anchor d-block animsition-link" href="{% url 'store:product-detail' cart_product.product.slug %}"><img src="{{cart_product.product.product_image.url}}" alt="{{cart_product.product.title}}" width="70"/></a>
                          {% else %}
                            <a class="reset-anchor d-block animsition-link" href="{% url 'store:product-detail' cart_product.product.slug %}"><img src="{% static 'img/product-detail-3.jpg' %}" alt="{{cart_product.product.title}}" width="70"/></a>
                          {% endif %}

                          <div class="media-body ml-3"><strong class="h6"><a class="reset-anchor animsition-link" href="{% url 'store:product-detail' cart_product.product.slug %}">{{cart_product.product.title}}</a></strong></div>
                        </div>
                      </th>
                      <td class="align-middle border-0"><a class="reset-anchor" href="{% url 'store:remove-wishlist' cart_product.id %}"><i class="fas fa-trash-alt small text-muted"></i></a></td>
                    </tr>
                    {% endfor %}

                  </tbody>
                </table>
              </div>
          </div>
        </section>
        
        {% else %}

          <div class="text-center py-5">
            <h3 class="mb-3">Your wishlist is empty.</h3>
            <a href="{% url 'store:home' %}"><i class="fas fa-long-arrow-alt-left mr-2"> </i>Continue shopping</a>
          </div>

        {% endif %}

      </div>
      {% endblock content %}

      {% block payment-gateway %}
        <!-- Include the PayPal JavaScript SDK -->
    <script src="https://www.paypal.com/sdk/js?client-id=YOUR-PAYPAL-CLIENT-ID&currency=USD"></script>

    <script>
        // Render the PayPal button into #paypal-button-container
        paypal.Buttons({

            // Set up the transaction
            createOrder: function(data, actions) {
                return actions.order.create({
                    purchase_units: [{
                        amount: {
                            value: '{{total_amount}}'
                        }
                    }]
                });
            },

            // Finalize the transaction
            onApprove: function(data, actions) {
                return actions.order.capture().then(function(details) {
                    // Show a success message to the buyer
                    alert('Transaction completed by ' + details.payer.name.given_name + '!');
                    // Savind Order in Database after Payment Success
                    document.getElementById('myform').submit();
                });
            }


        }).render('#paypal-button-container');
    </script>
      {% endblock payment-gateway %}